pretrained_base_model_path: "./pretrained_weights/sd-image-variations-diffusers"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
audio_model_path: "./pretrained_weights/audio_processor/whisper_tiny.pt"
denoising_unet_path: "./pretrained_weights/denoising_unet_pose.pth"
reference_unet_path: "./pretrained_weights/reference_unet_pose.pth"
face_locator_path: "./pretrained_weights/face_locator_pose.pth"
motion_module_path: "./pretrained_weights/motion_module_pose.pth"
inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'
test_cases:
  "/home/salman/face/assets/face.png":
    - "/home/salman/face/news_audio_short.wav"
    - "/home/salman/face/echomimic/assets/compare_pose_360"
